### ISSUE TITLE
Does the kernel not support？

### ISSUE THREAD

**Issue by simrty** [gwlim/Openwrt_Firmware#10]
hi，The device that I use is Netgear wndr4300 ，I used your firmware，The kernel version is 4.4.74，Does it support USB？

opkg install kmod-usb-ohci 

 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-ohci:
 * 	kernel (= 4.4.71-1-7163756290c10ef7734df504f3a8958b) * 
 * opkg_install_cmd: Cannot install package kmod-usb-ohci.

Thank you!

**Comment by gwlim** [comment]
https://github.com/gwlim/Fast-Path-LEDE-OpenWRT
