### ISSUE TITLE
pptpd

### ISSUE THREAD

**Issue by hova888** [gwlim/Openwrt_Firmware#8]
Hi tnx awesome work...my tl wdr 4300 one problem i install this build https://github.com/gwlim/Openwrt_Firmware/blob/master/TP-Link_TL-WDR3500-3600-43XX-WM4350R/Barrier_Breaker/Dec-2015-Image/openwrt-ar71xx-generic-tl-wdr4300-v1-squashfs-sysupgrade.bin
but i not install
opkg install pptpd
Downloading http://downloads.openwrt.org/barrier_breaker/14.07/a….4.0-1_ar71xx.ipk. Multiple packages (kmod-ppp and kmod-ppp) providing same name marked HOLD or PREFER. Using latest. Multiple packages (kmod-gre and kmod-gre) providing same name marked HOLD or PREFER. Using latest. Multiple packages (kmod-mppe and kmod-mppe) providing same name marked HOLD or PREFER. Using latest. Configuring pptpd.
Help me plz

**Comment by gwlim** [comment]
It is normal OpenWrt LEDE builds kernel modules tagged to kernel version, I no longer make binaries as it is too much work, but you can still build from my source
