### ISSUE TITLE
WDR3500 Build

### ISSUE THREAD

**Issue by stmblfrcr** [gwlim/Openwrt_Firmware#9]
Hi,
sorry, I hope it's fine, that I'm asking here - would you mind, doing another recent LEDE 17.01. build for the WDR3500? Would really appreciate it. Thanks and regards.

**Comment by gwlim** [comment]
ok but note that there will not be Hardware NAT because it does not have a dedicated switch chip.
It uses the internal 	AR934X built-in switch which is why it is only 100Mbps capable
https://wiki.openwrt.org/toh/tp-link/tl-wdr3500

**Comment by stmblfrcr** [comment]
Thank you! That's fine, I'm interested how the rest of your patches work out as well.

**Comment by stmblfrcr** [comment]
Would you care for another WDR3500 build with Fast Path included? Would it even make sense (at least for wireless performance)? Thanks.

**Comment by gwlim** [comment]
Will do this weekend

**Comment by stmblfrcr** [comment]
Thanks. Much appreciated!
